import React, { ReactNode } from "react";
import Nav from "../Nav";
import Head from "next/head";

type Props = {
	children: ReactNode;
};

function MainLayout({ children }: Props) {
	return (
		<>
			<Head>
				<title>Honey Badgers Next.js</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				style={{
					minHeight: "100vh",
					display: "flex",
					flexDirection: "column",
				}}>
				<Nav />
				<div>{children}</div>
				<div
					style={{
						marginTop: "auto",
						height: "50px",
						padding: "1em",
						border: "solid 1px black",
						textAlign: "right",
					}}>
					This is the footer
				</div>
			</div>
		</>
	);
}

export default MainLayout;
